version: "3.6"
services:
  productservice_postgres:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=product
    ports:
      - "5432:5432"
    volumes:
      - ./docker_productservice_postgres_init.sql:/docker-entrypoint-initdb.d/docker_productservice_postgres_init.sql
    command: -p 5432

  orderservice_postgres:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=order
    ports:
      - "5433:5433"
    volumes:
      - ./docker_orderservice_postgres_init.sql:/docker-entrypoint-initdb.d/docker_orderservice_postgres_init.sql
    command: -p 5433

  ticketservice_postgres:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ticket
    ports:
      - "5434:5434"
    volumes:
      - ./docker_ticketservice_postgres_init.sql:/docker-entrypoint-initdb.d/docker_ticketservice_postgres_init.sql
    command: -p 5434
