eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/order
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      bindings:
        input:
          binder: kafka
          destination: productEventTopic
          content-type: application/json
          group: input-group-1
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost